roles:
  - root@超级用户
  - normal@登录用户
  - vistor@游客
permissions:
  - cart-item/create@加入购物车动作
  - cart-item/update@更新购物车条目
  - cart-item/delete@加入购物车动作
  - cart-item/list@查询购物车条目
  - lattr/create@
  - lattr/update@
  - lclassification/list@查询分类信息
  - >
    lclassification/update@更新分类信息
  - >
    lclassification/delete@删除分类信息
  - >
    lclassification/create@创建一个分类信息
  - lcollect/view@获取属性集合详情
  - lcollect/list@
  - lcollect/create@创建属性集合
  - lcollect/update@
  - lgoods/handle@
  - lgoods/list@查询商品接口
  - lgoods/view-sku@
  - lgoods/view@查看商品信信息
  - lgoods/list-attrs@
  - lgoods/update@修改一个商品
  - lgoods/create@创建一个商品
  - lorder/list@获取订单详情
  - lorder/view@获取订单详情
  - lorder/create@创建一条订单
  - lorder/create-trans@创建一条订单
  - lrefund/create@
  - lrefund/update-status@
  - >
    lsale-rule/create@创建一条销售规则
  - >
    lsale-rule/update@创建一条销售规则
  - lsale-rule/list@查询销售规则
  - ltrans/create-pay-order@
  - lfile/index@
  - lfile/delete@
  - lfile/list@
  - lfile/chunk-task-create@
  - lfile/create@上传一个文件
  - lfile/output@
  - lbanner/list@创建banner图
  - lbanner/view@获取banner图详情信息
  - lbanner/delete@删除banner图
  - lbanner/create@创建banner图
  - lbanner/update@修改banner图
  - >
    lauth/login@登录用户获取访问token
  - lauth/get-info@
  - lauth/logout@
  - luser/update@
  - luser/view@
  - luser/list@
  - luser/create@创建用户
  - 'lgoods/*@商品的全部权限'
  - 'lattr/*@属性管理全部权限'
  - 'lclassification/*@分类管理全部权限'
  - 'lorder/*@订单管理全部权限'
  - 'lcollect/*@属性集合全部管理权限'
  - 'lrefund/*@售后管理全部权限'
  - 'lsale-rule/*@销售规则管理全部权限'
  - 'lfile/*@文件管理全部权限'
  - 'ltrans/*@交易管理全部权限'
  - 'lbanner/*@banner图全部管理权限'
  - 'lauth/*@认证管理全部权限'
  - 'luser/*@用户管理全部权限'
assign:
  - root@lgoods/handle
  - root@lgoods/list
  - root@lgoods/view-sku
  - root@lgoods/view
  - root@lgoods/list-attrs
  - root@lgoods/update
  - root@lgoods/create
  - root@lattr/create
  - root@lattr/update
  - root@lclassification/list
  - root@lclassification/update
  - root@lclassification/delete
  - root@lclassification/create
  - root@lorder/list
  - root@lorder/view
  - root@lorder/create
  - root@lorder/create-trans
  - root@lrefund/create
  - root@lrefund/update-status
  - root@lsale-rule/create
  - root@lsale-rule/update
  - root@lsale-rule/list
  - root@lfile/index
  - root@lfile/delete
  - root@lfile/list
  - root@lfile/chunk-task-create
  - root@lfile/create
  - root@lfile/output
  - root@lauth/login
  - root@lauth/get-info
  - root@lauth/logout
  - root@luser/update
  - root@luser/view
  - root@luser/list
  - root@luser/create
  - root@lcollect/view
  - root@lcollect/list
  - root@lcollect/create
  - root@lcollect/update
  - root@ltrans/create-pay-order
  - root@lbanner/list
  - root@lbanner/view
  - root@lbanner/delete
  - root@lbanner/create
  - root@lbanner/update
  - normal@lauth/login
  - normal@lgoods/list
  - normal@lgoods/view
  - normal@lfile/create
  - vistor@lauth/login
  - vistor@lgoods/list
  - vistor@lgoods/view
