roles:
  - root@超级用户
  - normal@登录用户
  - vistor@游客
permissions:
  - goods/handle@
  - goods/list@查询商品接口
  - goods/view-sku@
  - goods/view@查看商品信信息
  - goods/list-attrs@
  - goods/update@修改一个商品
  - goods/create@创建一个商品
  - lattr/create@
  - lattr/update@
  - lclassification/list@查询分类信息
  - >
    lclassification/update@更新分类信息
  - >
    lclassification/delete@删除分类信息
  - >
    lclassification/create@创建一个分类信息
  - lcollect/view@获取属性集合详情
  - lcollect/list@
  - lcollect/create@创建属性集合
  - lcollect/update@
  - lorder/list@获取订单详情
  - lorder/view@获取订单详情
  - lorder/create@创建一条订单
  - lorder/create-trans@创建一条订单
  - lrefund/create@
  - lrefund/update-status@
  - >
    lsale-rule/create@创建一条销售规则
  - >
    lsale-rule/update@创建一条销售规则
  - lsale-rule/list@查询销售规则
  - ltrans/create-pay-order@
  - lfile/index@
  - lfile/delete@
  - lfile/list@
  - lfile/chunk-task-create@
  - lfile/create@上传一个文件
  - lfile/output@
  - lbanner/list@创建banner图
  - lbanner/view@获取banner图详情信息
  - lbanner/delete@删除banner图
  - lbanner/create@创建banner图
  - lbanner/update@修改banner图
  - auth/login@
  - auth/get-info@
  - auth/logout@
  - user/update@
  - user/view@
  - user/list@
  - user/create@
  - 'goods/*@商品的全部权限'
  - 'lattr/*@属性管理全部权限'
  - 'lclassification/*@分类管理全部权限'
  - 'lorder/*@订单管理全部权限'
  - 'lrefund/*@售后管理全部权限'
  - 'lsale-rule/*@销售规则管理全部权限'
  - 'lfile/*@文件管理全部权限'
  - 'auth/*@认证管理全部权限'
  - 'user/*@用户管理全部权限'
assign:
  - root@goods/handle
  - root@goods/list
  - root@goods/view-sku
  - root@goods/view
  - root@goods/list-attrs
  - root@goods/update
  - root@goods/create
  - root@lattr/create
  - root@lattr/update
  - root@lclassification/list
  - root@lclassification/update
  - root@lclassification/delete
  - root@lclassification/create
  - root@lorder/list
  - root@lorder/view
  - root@lorder/create
  - root@lorder/create-trans
  - root@lrefund/create
  - root@lrefund/update-status
  - root@lsale-rule/create
  - root@lsale-rule/update
  - root@lsale-rule/list
  - root@lfile/index
  - root@lfile/delete
  - root@lfile/list
  - root@lfile/chunk-task-create
  - root@lfile/create
  - root@lfile/output
  - root@auth/login
  - root@auth/get-info
  - root@auth/logout
  - root@user/update
  - root@user/view
  - root@user/list
  - root@user/create
  - normal@auth/login
  - normal@goods/list
  - normal@goods/view
  - normal@lfile/create
  - vistor@auth/login
  - vistor@goods/list
  - vistor@goods/view
